### ISSUE TITLE
CCIP - #01 Approval Process for Third-Party Vendors

### ISSUE THREAD

**Issue by HiGregory** [citycoins/governance#1]
CCIP-01: Approval Process For Third-Party Vendors
Author(s): @GregoryJohnson,
Start Date: 2022-03-13
Category: Data Governance
Tracking Issue: 
Status: Draft
Summary
This proposal seeks to layout requirements for third-party vendors to be approved by the community, and a process led by Cities themselves to select vendors to implement CityCoins in their workflows to solve problems they prioritize. 

For MiamiCoin, there are vendors working specifically on implementation that should be flagged as verified by the community to increase participation. 
## Motivation
- In order to succeed, the CityCoin network will require usage, and utility in cities to adopt it for the long term. To achieve that level, we will need vendors approved by Cities to work on solutions that are not led by Crypto-organizations.
- As of writing, there are approximately 2 cities with Mayors who approved CityCoin: MIA and NYC. To get real scale, the network will need usage and adoption linked to a tangible goal that is not set on payments. 
- Currently, DataGovs Inc is an approved vendor for the City of Miami working on supporting the adoption of the token for supporting departmental needs. 
-  Currently, CityCoins and Stacks Accelerator are vehicles being used to accelerate adoption. There is a lot of criticism around CityCoins due to the lack of utility and pathways for success that start with problems - not the price of the token. 

##Stakeholders
Almost everyone involved in the CityCoins ecosystem, but especially:
- Prospective third-party vendors
- Prospective CityCoin new cities, which might be deterred by lack of utility, features, or problems to be solved. 
- Current holders of the token
- City's that adopt a token based on Stack-based CityCoins

##Detailed Explanation
This document attempts to outline:
- Requirements and process for applications by third-party vendors (City-approved)
- A rough process for CityCoins to list vendors for referencing by the public
- Expectations for software maintenance and customer support from these vendors

For an initial launch, we propose favoring:
- Community members vendors with demonstrated experience in government, technology, and crypto/blockchain-related productions
- Existing vendors of Cities that work on various roles related to finance, data, or other departmental needs. 

Since this is a brand-new initiative and there is potential for abuse or failure to deliver, we seek to minimize risk. Over time, we would like to open this up to new entrants, and more experimental designs.

## Application Requirements
Prospective vendors would be expected to provide:
- Detailed software designs and prototypes that well explain a problem to be solved
- Demonstrated experience with software-related government or crypto-based projects
- Evidence of a functioning prototype. 
- Proof of reliable software configuration.
- A list of other potential risks and issues

##**Success Metrics**

- Number of approved third-party vendors
- Number of actual applications and users adoption
- The number of cities that are supported by each or multiple vendors.

**Comment by whoabuddy** [comment]
Hey Gregory, just a quick update that this is still on our radar, let's still plan to revisit this after the community upgrade is complete.

**Comment by HiGregory** [comment]
Hi @whoabuddy - Thanks for the update. 

Our API is up and enabling cities and teams to track data issues and we want to enable CC use cases for  City of Miami.

**Comment by whoabuddy** [comment]
Closing this out as it didn't materialize into action, feel free to re-open or create a new CCIP if warranted.
