### ISSUE TITLE
Extend direct-execute sunset period

### ISSUE THREAD

**Issue by whoabuddy** [citycoins/governance#17]
The direct execute extension has a sunset period of ~6 months from deployment, or 25,920 Stacks blocks.

```clarity
(define-data-var sunsetBlock uint (+ block-height u25920))
```

As [seen on the explorer](https://explorer.hiro.so/txid/SP8A9HZ3PKST0S42VM9523Z9NV42SZ026V4K39WH.ccd001-direct-execute?chain=mainnet), the contract was deployed at block height 95,988.

`95,988 + 25,920 = 121,908`

Currently we are at **Stacks block 119,028**, leaving ~2,880 blocks before it expires. We should create a CCIP and contract proposal that:
- allows for a vote from stackers in past cycles (same as before)
- verifies the vote before executing the contract change
- updates the sunset block expiry by another 25,920 blocks (~6 months)

During that time we can continue to review and fomrulate any outstanding CCIPs, as well as look at integrating the voting method used in proposals into something used by the direct execute extension itself instead.

Side note: there is no getter for the variable in this version, but that would be a great thing to note for a v2!

**Comment by CrypDohDS** [comment]
CCIP-17 Proposal: Extend CCD01-direct -execute to STX Block 147,828 (appx 6mos)

**Comment by whoabuddy** [comment]
@CrypDohDS thanks! Details outlined in a draft CCIP in the linked PR, see [the text here](https://github.com/citycoins/governance/blob/feat/add-ccip-017/ccips/ccip-017/ccip-017-extend-direct-execute-sunset-period.md) and open to feedback!

**Comment by CrypDohDS** [comment]
Do we need much discussion or just move to vote?DSSent from my iPhoneOn Aug 31, 2023, at 6:30 PM, Jason Schrader ***@***.***> wrote:﻿
@CrypDohDS thanks! Details outlined in a draft CCIP in the linked PR, see the text here and open to feedback!
