### ISSUE TITLE
Request for Proposal CCIP-18

### ISSUE THREAD

**Issue by CrypDohDS** [citycoins/governance#19]
There are few or limited CityCoins user interfaces applications and web development. The CityCoins needs additional development. This issue is a request for proposal for CCIP 18 to form the city coins, global Decentralized, autonomous organization. In structure this proposal should request a community vote using CCIP-15 voting method to dedicate 2% of stacking rewards per cycle to a dedicated treasury and immediately upon approval funds with 2000 STX stacks, tokens from existing city wallets. These funds will be community approved on all future votes. This open issue, request amendment and modification from the community.

**Comment by Rapha-btc** [comment]
Here's a very rough UI at https://www.jing.cash/ — efficient and reliable without API calls or deny mode rolling back transactions.

**Comment by friedger** [comment]
Project is shutting down
