### ISSUE TITLE
CCIP-019: Stacks Nakamoto Release Preparation

### ISSUE THREAD

**Issue by whoabuddy** [citycoins/governance#23]
More to be added in a PR with a CCIP, but for now calling out some good info that came from the Discord discussion in #path-forward.

The Nakamoto release for the Stacks blockchain will bring 5 second block times to Stacks, which is a huge improvement in throughput compared to the 10 minute block times we see now.

CityCoins mining is based on Stacks blocks, and the [issuance schedule in CCIP-012](https://github.com/citycoins/governance/blob/main/ccips/ccip-012/ccip-012-stabilize-emissions-and-treasuries.md#phase-1-reduce-citycoin-emissions) expects blocks to be produced at the rate of Bitcoin blocks, or on average every 10 minutes.

If not updated, this would result in CityCoins being issued at >100x the expected rate, and there were a few options discussed:

## Reduce emissions amount per block

This would fix the extra emissions due to faster blocks, but mining is limited to 200 blocks at a time, which would go from ~1.5 days down to ~15 minutes. 

## Spread mining over multiple blocks

This adds to the complexity and deviates from the original 1:1 relationship with issuance. 

## Tie mining to the burn block height (Bitcoin)

This looks like the simplest/cleanest solution with the goal of leaving things as-is.

It shouldn't require much modification to the current code as all mining data structures are based on a block height, and BTC block heights will have no collision with Stacks block heights.

Some UI lift will be required to make sure between mining and claiming things are smooth.

It would also require updating the coinbase thresholds so that they are based on Bitcoin blocks equivalent to where we are at in the current epoch (Stacks block 134,223 / BTC block 824,049 as of writing this).

---

Curious to hear thoughts from others, and will work on the CCIP draft next with more detail.

Great Nakamoto resource from `kilr_dad`:
https://stacksfoundation.notion.site/The-Ultimate-Stacks-Nakamoto-Guide-7360bc316dcb49e6a03699342f0523be#9691c85ba8eb45a09551162a7c91276e

**Comment by anibalbosco** [comment]
"Tie mining to the burn block height (Bitcoin)" seems to be the only option
that makes sense.

**Comment by whoabuddy** [comment]
Another great resource: https://stacks.org/halving-on-horizon-nakamoto

It looks like this will include a new version of the PoX contract (.pox-4), so we'll need to look at that within this CCIP as well.

**Comment by whoabuddy** [comment]
Looking at the protocol contracts, the following items directly reference `block-height` in code:

| where                                | what                                 | status                                         |
| ------------------------------------ | ------------------------------------ | ---------------------------------------------- |
| base-dao: executing a proposal       | block height stored when executed    | :heavy_check_mark: leave as-is                 |
| ccip-015: vote window for a proposal | if start and end block are specified | :grey_question: keep or use burn block height? |
| ccd-001: sunset block                | expiry block for ccd001 access       | :warning: recalculate expected value           |
| ccd-001: set sunset block            | compares to current Stacks block     | :heavy_check_mark: leave as-is                 |
| ccd-001: direct execute              | compares to current Stacks block     | :heavy_check_mark: leave as-is                 |
| ccd-006: citycoin mining             | mining data stored by block height   | :warning: update to use burn block height      |
| ccd-006: get coinbase amount         | coinbase determined by block height  | :warning: update to use burn block height      |
| ccd-008: set activation details      | block height stored when activated   | :grey_question: keep or use burn block height? |

In addition, the following data structures are based on the `block-height` directly or indirectly:

| where                       | what                            | status          |
| --------------------------- | ------------------------------- | --------------- |
| ccd-005: ActivationDetails  | succeededAt, delay, activatedAt | :grey_question: |
| ccd-005: CoinbaseThresholds | cbt1, cbt2, cbt3, cbt4, cbt5    | :grey_question: |
| ccd-005: CoinbaseDetails    | bonus, epoch                    | :grey_question: |
| ccd-006: MiningStats        | height                          | :grey_question: |
| ccd-006: Miners             | height                          | :grey_question: |
| ccd-006: HighValues         | height                          | :grey_question: |
| ccd-006: Winners            | height                          | :grey_question: |
| ccd-006: rewardDelay        | number of blocks                | :grey_question: |

These will all be areas to consider for updates in the CCIP and thoroughly test with the implementation.

**Comment by akilress** [comment]
I agree that this is the only, best way to do it.

**Comment by whoabuddy** [comment]
The SIP for the Nakomoto Release is available now as SIP-021: Fast and Reliable Blocks through PoX-assisted Block Propagation.

- [Pull request for SIP with comments](https://github.com/stacksgov/sips/pull/155)
- [Direct link to SIP text](https://github.com/stacksgov/sips/blob/feat/sip-021-nakamoto/sips/sip-021/sip-021-nakamoto.md)

There is an excerpt that [describes changes to the Clarity language](https://github.com/stacksgov/sips/blob/feat/sip-021-nakamoto/sips/sip-021/sip-021-nakamoto.md#changes-to-clarity), which may actually help our case:

![d785aa0ddbb098ed06855ddc2ad550a72ccb1b134270830edc3ecea8d2d71044](https://github.com/citycoins/governance/assets/9038904/543783bd-6039-42f9-a29f-9e3d6eb69853)

This would mean the `block-height` value in our contract would continue to evaluate to the "tenure height", which is increased once for every Bitcoin block and maintains the same cadence as before once Nakamoto activates.

@obycode can you confirm this or provide any insights? We're trying to narrow down what needs to be done as Nakamoto approaches.

---

Based on this I've updated the charts below:

| where                                | what                                 | status                                         |
| ------------------------------------ | ------------------------------------ | ---------------------------------------------- |
| base-dao: executing a proposal       | block height stored when executed    | :heavy_check_mark: leave as-is                 |
| ccip-015: vote window for a proposal | if start and end block are specified | :heavy_check_mark: leave as-is  |
| ccd-001: sunset block                | expiry block for ccd001 access       | :heavy_check_mark: leave as-is           |
| ccd-001: set sunset block            | compares to current Stacks block     | :heavy_check_mark: leave as-is                 |
| ccd-001: direct execute              | compares to current Stacks block     | :heavy_check_mark: leave as-is                 |
| ccd-006: citycoin mining             | mining data stored by block height   | :heavy_check_mark: leave as-is      |
| ccd-006: get coinbase amount         | coinbase determined by block height  | :heavy_check_mark: leave as-is     |
| ccd-008: set activation details      | block height stored when activated   | :heavy_check_mark: leave as-is |

Everything above would continue to operate as expected. Any *new contracts* deployed after Nakamoto will have to use the `tenure-height` variable to match the functionality of `block-height` in the older contracts.

In addition, the following data structures are based on the `block-height` directly or indirectly:

| where                       | what                            | status          |
| --------------------------- | ------------------------------- | --------------- |
| ccd-005: ActivationDetails  | succeededAt, delay, activatedAt | :heavy_check_mark: leave as-is |
| ccd-005: CoinbaseThresholds | cbt1, cbt2, cbt3, cbt4, cbt5    | :heavy_check_mark: leave as-is |
| ccd-005: CoinbaseDetails    | bonus, epoch                    | :heavy_check_mark: leave as-is |
| ccd-006: MiningStats        | height                          | :heavy_check_mark: leave as-is |
| ccd-006: Miners             | height                          | :heavy_check_mark: leave as-is |
| ccd-006: HighValues         | height                          | :heavy_check_mark: leave as-is |
| ccd-006: Winners            | height                          | :heavy_check_mark: leave as-is |
| ccd-006: rewardDelay        | number of blocks                | :heavy_check_mark: leave as-is |

---

The Nakamoto release will still require an update to the treasury contracts to interact with the new `pox-4` contract, and the mining contract will require an update as well to use the new treasury contract. The CCIP will go into more detail for the changes required.

**Comment by akilress** [comment]
When is this CCIP going to be voted on?

**Comment by friedger** [comment]
Project is shutting down
