### ISSUE TITLE
Extend Direct execute CCD-001

### ISSUE THREAD

**Issue by CrypDohDS** [citycoins/governance#26]
Previously it was voted and passed in CCIP-17, CCIP-14 and resolved issue 18 to extend the sunset direct execute in CCD001. 

Currently we are at Stacks block 144576 leaving ~3252 blocks or 22 days (April 18, 2024) before it expires. We should create a CCIP and contract proposal that:

allows for a vote from stackers in 2 recent cycles (same as before)
verifies the vote before executing the contract change
updates the sunset block expiry by another 100,000 blocks (~20 months).

**Comment by CrypDohDS** [comment]
Updated text

**Comment by akilress** [comment]
I apologize for not having a lot of technical input.

However, I think it would be fine to proceed as you suggest

**Comment by CrypDohDS** [comment]
Updated text. 3252 blocks left
